// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcrvzvxpjapijltagaxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjcnZ6dnhwamFwaWpsdGFnYXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjMyMjIsImV4cCI6MjA3MTEzOTIyMn0.sZIRgBvn3_IO6VP_O1JUQHlv2AadqKN_fRv8eX2xjaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});